window.addEventListener('keyup', function (event) {
  switch (event.keyCode) {
    case 49: // 1
    $(".card_active").removeClass("card_active");
    $(".sun").addClass("card_active");
    sun.position.set( -580, 50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 50: // 2
    $(".card_active").removeClass("card_active");
    $(".marcury").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, 50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 51: // 3
    $(".card_active").removeClass("card_active");
    $(".venus").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, 50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 52: // 4
    $(".card_active").removeClass("card_active");
    $(".earth").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, 50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 53: // 5
    $(".card_active").removeClass("card_active");
    $(".moon").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, 50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 54: // 6
    $(".card_active").removeClass("card_active");
    $(".mars").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, 50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 55: // 7
    $(".card_active").removeClass("card_active");
    $(".jupiter").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , 50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 56: // 8
    $(".card_active").removeClass("card_active");
    $(".suturn").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, 50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 57: // 9
    $(".card_active").removeClass("card_active");
    $(".uranus").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, 50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 48: // 0
    $(".card_active").removeClass("card_active");
    $(".neptune").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, 50, 0);
    pluto.position.set(sunDistance + 620, -50, 0);
      break;
    case 189: // 11
    $(".card_active").removeClass("card_active");
    $(".pluto").addClass("card_active");
    sun.position.set( -580, -50, 0);
    mercury.position.set(sunDistance - 500, -50, 0);
    venus.position.set(sunDistance - 410, -50, 0);
    earth.position.set(sunDistance - 300, -50, 0);
    moon.position.set(sunDistance - 230, -50, 0);
    mars.position.set(sunDistance -150, -50, 0);
    jupiter.position.set(sunDistance , -50, 0);
    saturn.position.set(sunDistance + 170, -50, 0);
    uranus.position.set(sunDistance + 320, -50, 0);
    neptune.position.set(sunDistance + 470, -50, 0);
    pluto.position.set(sunDistance + 620, 50, 0);
      break;
      case 187: // 12
    $(".card_active").removeClass("card_active");
    sun.position.set( -580, 0, 0);
    mercury.position.set(sunDistance - 500, 0, 0);
    venus.position.set(sunDistance - 410, 0, 0);
    earth.position.set(sunDistance - 300, 0, 0);
    moon.position.set(sunDistance - 230, 0, 0);
    mars.position.set(sunDistance -150, 0, 0);
    jupiter.position.set(sunDistance , 0, 0);
    saturn.position.set(sunDistance + 170, 0, 0);
    uranus.position.set(sunDistance + 320, 0, 0);
    neptune.position.set(sunDistance + 470, 0, 0);
    pluto.position.set(sunDistance + 620, 0, 0);
      break;
    default:
  }
});